# Site settings
title: Andor Chen
author: 安道
email: andor.chen.27@gmail.com
description: 安道的个人网站
baseurl: ""
url: "http://about.ac"
twitter_username: andor_chen
github_username:  andorchen

# Build settings
permalink: /:year/:month/:title.html
exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock", 'node_modules', 'package.json', 'gulpfile.js']
keep_files: ['.git', '.gitignore', '.git-ftp-ignore']
timezone: '+0800'

# Converter settings
markdown: ACKramdownParser
kramdown:
  input: GFM
  auto_ids: false
  enable_coderay: false
  syntax_highlighter: rouge

collections:
  books:
    output: true
    permalink: /:collection/:path/
