# Site settings
title: Andor Chen
author: 安道
email: andor.chen.27@gmail.com
description: 安道的个人网站
baseurl: ""
url: "https://about.ac"
twitter_username: andor_chen
github_username:  andorchen

# Build settings
permalink: /:year/:month/:title.html
exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock", 'node_modules', 'package.json', 'gulpfile.js']
keep_files: ['.git', '.nojekyll']
timezone: '+0800'

# Converter settings
markdown: ACKramdownParser
kramdown:
  input: GFM
  auto_ids: false

sass:
  style: compressed

collections:
  books:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ''
      type: 'books'
    values:
      layout: 'book'
      body_class: 'book-page'

  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      body_class: 'single-post-page'
