pygments: true
markdown: redcarpet
redcarpet:
  extentions: ['fenced_code_blocks', 'strikethrough', 'space_after_headers', 'tables']
permalink: /:year/:month/:title.html
exclude: [".ruby-version", "README.md", "Rakefile", "about.ac.sublime-project", "about.ac.sublime-workspace", "Gemfile", "Gemfile.lock", "bin"]
keep_files: ['.git', '.nojekyll', 'CNAME']

title: Andor Chen
tagline: Andor 的个人网站
author:
  name: Andor
  full_name: Andor Chen
  bio: Andor 是一位父亲、丈夫，也是一名机械工程师。使用 WordPress 几年后，将个人网站转换到 Jekyll 平台。目前正在学习 Ruby。
  email: Andor.Chen.27@gmail.com

production_url: http://about.ac

JB:
  version: 0.2.13

  BASE_PATH: false
  ASSET_PATH: false

  archive_path: /pages/archive.html
  categories_path: /pages/categories.html
  tags_path: /pages/tags.html

  comments:
    provider: false

  analytics:
    provider: false
    google:
      tracking_id: 'UA-123-12'

  sharing:
    provider: false

  tags_list:
    provider: 'custom'

  posts_collate:
    provider: 'custom'

  pages_list:
    provider: 'custom'
