# Site settings
title: Andor Chen
author: 安道
author_info: 安道是一位父亲、丈夫，一名机械工程师。翻译爱好者，已出版几本电子书。偶尔写些代码。
email: andor.chen.27@gmail.com
description: 安道的个人网站
baseurl: ""
url: "http://about.ac"
twitter_username: andor_chen
github_username:  andorchen

# Build settings
permalink: /:year/:month/:title.html
exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
keep_files: ['.git', '.nojekyll', 'CNAME', 'assets', 'favicon.ico']

# Converter settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  use_coderay: false
  syntax_highlighter: rouge
